version: "3.1"

services:
  app:
    container_name: full_app
    build: .
    ports: 
      - 4000:4000
    restart: on-failure
    volumes:
        - api:/usr/src/app/
    depends_on:
        - db
        #- migrate      
    networks:
        - fullstack

  db:
    image: postgres:latest
    container_name: db_postgres
    environment:
      - POSTGRES_USER=${DB_USER}  
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST} 
    ports:
      - "5432:5432"
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - fullstack


#  migrate:
#   image: migrate/migrate
#    networks:
#     - new
#    volumes:
#      - .:/migrations
#    command: ["-path", "/migrations", "-database", "postgres://buscompanion:password@database:5432/buscompanion?sslmode=disable", "up", "3"]
#    links:
#      - db

volumes:
  api:
  database_postgres:
networks:
    fullstack:
      driver: bridge

