version: "3.1"

services:
  db:
    image: postgres:latest
    container_name: db_postgres
    environment:
      - PG_USER=${DB_USER}  
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST} 
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${DB_NAME} -U ${DB_USER}"]
      interval: 10s
      timeout: 30s
      retries: 5
    networks:
      - fullstack

  app:
    container_name: full_app
    build: .
    ports: 
      - 4000:4000
    restart: on-failure
    volumes:
        - api:/usr/src/app/
    depends_on:
        - db
        #- migrate      
    networks:
        - fullstack

  migrate:
    image: migrate/migrate
    networks:
      - fullstack
    volumes:
      - .:/migrations/migrations
    entrypoint: migrate
    command: -path /migrations -database ${POSTGRES_URL} -verbose up
    depends_on:
      db:
        condition: service_healthy

volumes:
  api:
networks:
    fullstack:
      driver: bridge

